### ISSUE TITLE
Miele not active

### ISSUE THREAD

**Issue by bsoener** [QuickSander/homebridge-mieleathome#11] opened 2021-01-30 17:04 UTC
First of all thank you for providing for the app. Have configured and set up the method 1. what I noticed today is that now my Miele wash does but at the homkekit app as is turned off? thanks for the help.

<img width="111" alt="Bildschirmfoto 2021-01-30 um 17 58 34" src="https://user-images.githubusercontent.com/77502899/106362874-7e5e9680-6325-11eb-8622-3113d0f2c5c8.png">

**Comment by bsoener** [comment] 2021-01-31 16:01
Does no one have an idea what this can be?
When I do method 2, it works strangely enough

**Comment by QuickSander** [comment] 2021-02-01 21:41
Hi,
It shouldn't matter which method you used. 

I am in the process of creating a guided setup which would get rid of most manual actions and should prevent any wrongly retrieved tokens. If this persists please add the Homebridge logging preferably with debug mode enabled.

**Comment by QuickSander** [comment] 2021-02-06 21:02
Guided setup process is now available in the newest version.

**Comment by bsoener** [comment] 2021-02-07 15:52
Update was performed yesterday evening. Today the washing machine runs but the plugin shows the device is offline? Do I need to update my tokens again?

**Comment by QuickSander** [comment] 2021-02-07 19:05
Please paste your log information.  Then I can see how the plugin has stored your tokens or if it uses your config as last resort.

**Comment by bsoener** [comment] 2021-02-07 19:46
{
            "name": "Miele@Home",
            "clientID": "729ec637-4a22-4694-9f12-5e837160xxxx",
            "clientSecret": "pIzmliEmaTYDCZzgu94nem2f1r7Axxxx",
            "token": "DE_733dcdd4badb9804132a68b58944xxxx",
            "refreshToken": "DE_2d9170f8405a2ad8171467e70c99xxxx",
            "language": "de",
            "pollInterval": 60,
            "platform": "Miele@home"
        },


[07/02/2021, 16:49:07] [Homebridge UI] [homebridge-mieleathome] Incoming Request: /is_token_stored
[07/02/2021, 16:49:07] [Homebridge UI] [homebridge-mieleathome] Valid token already available in persistent storage.
[07/02/2021, 16:49:18] [Homebridge UI] [homebridge-mieleathome] Terminating child process...
[07/02/2021, 16:49:18] [Homebridge UI] [homebridge-mieleathome] Child process ended

**Comment by QuickSander** [comment] 2021-02-07 19:50
Please also dump the part of the log where the plugin attempts to connect to Miele. This should appear after pollInterval (60s). Then also the initialisation part where the plugin logs itself initialising. 
The token and refreshToken mentioned in your config are obsolete with the latest version. I think the plugin did not manage to refresh earlier due to connection problems.

**Comment by bsoener** [comment] 2021-02-07 19:53
In the log I only see this part. That means I would have to reconfigure the token again?

**Comment by QuickSander** [comment] 2021-02-07 19:59
No, I see you somehow again have a capital "H" in your config. If you only see that, it means the whole plugin did not load.
Please correct "H" in "h" for the platform name.

I do not understand though that when you press "Save" in settings, it should have saved the correct name.

**Comment by bsoener** [comment] 2021-02-07 20:05
{
            "name": "Miele@home",
            "clientID": "729ec637-4a22-4694-9f12-5e837160xxxx",
            "clientSecret": "pIzmliEmaTYDCZzgu94nem2f1r7Axxxx",
            "token": "DE_733dcdd4badb9804132a68b58944xxxx",
            "refreshToken": "DE_2d9170f8405a2ad8171467e70c99xxxx",
            "language": "de",
            "pollInterval": 60,
            "platform": "Miele@home"
        },

Has been modified and restarted. Unfortunately, it shows me in the Homekit that my Miele device is offline.

**Comment by QuickSander** [comment] 2021-02-07 20:08
Please paste your complete log, as the problem is the whole plugin is not even loaded. So it is not even touching any code of the plugin yet. 

You should see: 

[2/7/2021, 8:57:01 PM] Loaded config.json with 0 accessories and 2 platforms.
[2/7/2021, 8:57:01 PM] ---
[2/7/2021, 8:57:03 PM] Loaded plugin: homebridge-config-ui-x@4.36.0
[2/7/2021, 8:57:03 PM] Registering platform 'homebridge-config-ui-x.config'
[2/7/2021, 8:57:03 PM] ---
**[2/7/2021, 8:57:03 PM] Loaded plugin: homebridge-mieleathome@0.0.0-development**
**[2/7/2021, 8:57:03 PM] Registering platform 'homebridge-mieleathome.Miele@home'**
[2/7/2021, 8:57:03 PM] ---
[2/7/2021, 8:57:03 PM] Loading 2 platforms...
[2/7/2021, 8:57:03 PM] [Miele@home] Initializing Miele@home platform...
[2/7/2021, 8:57:03 PM] [Miele@home] Finished initializing platform: Miele@home
[2/7/2021, 8:57:03 PM] [Miele@home] Loading accessory data from cache: Washer dryer
[2/7/2021, 8:57:03 PM] [Miele@home] Executed didFinishLaunching callback
[2/7/2021, 8:57:03 PM] [Miele@home] Token loaded from persistent storage.

**Comment by bsoener** [comment] 2021-02-07 20:18
[30/01/2021, 12:35:50] ---
[30/01/2021, 12:35:50] Loaded plugin: homebridge-mieleathome@2.1.2
[30/01/2021, 12:35:50] Registering platform 'homebridge-mieleathome.Miele@home'
[30/01/2021, 12:35:50] ---

**Comment by QuickSander** [comment] 2021-02-07 20:21
That is an old log. Please reboot your Homebridge server and check the log. If you do not see "Initializing Miele@home" something very awkward is wrong outside of the code of this plugin.

**Comment by bsoener** [comment] 2021-02-07 20:22
which command do i have to enter?

sudo journalctl -f -au homebridge?

**Comment by QuickSander** [comment] 2021-02-07 20:25
Easiest is using the Homebridge Config UI-X. Upper right corner there is button with tooltip: "restart".
Via command line it is dependent on what configuration / install / OS you have to be able to answer that correctly.

**Comment by bsoener** [comment] 2021-02-07 20:33
Feb 07 21:24:08 raspberrypi homebridge[29823]: [07/02/2021, 21:24:08] [Miele@home] Miele API request https://api.mcs3.miele.com/v1/devices?language=de failed with status 401: "Unauthorized".

What I do not understand, before the update it did not work. I have set the tokens correctly. Then I saw that yesterday evening an update was out. This morning my washing machine is running but still shows my Homekit that it is offline....

**Comment by QuickSander** [comment] 2021-02-07 20:37
"before the update it did not work." So can I conclude it never worked? As you say "before the update .. " and "still shows offline"

This is understandable as it says: "Unauthorised".
Please realise that when there is a token available on disk, the plugin will always use that one. It will not use the one in your config, that is only used the very first startup. 

Please trigger setup by removing the Miele@home complete config section via the "config" tab in Config-UI-X.

**Comment by bsoener** [comment] 2021-02-07 20:48
On the homebridge configuration editor you mean?

        {
            "name": "Miele@home",
            "clientID": "729ec637-4a22-4694-9f12-5e837160xxxx",
            "clientSecret": "pIzmliEmaTYDCZzgu94nem2f1r7Axxxx",
            "token": "DE_733dcdd4badb9804132a68b58944xxxx",
            "refreshToken": "DE_2d9170f8405a2ad8171467e70c99xxxx",
            "language": "de",
            "pollInterval": 60,
            "platform": "Miele@home"
        },

the tokens were recreated 1 week before the update. Are just not so old.

**Comment by QuickSander** [comment] 2021-02-07 20:50
Yes, remove that complete block, that will trigger the setup when you enter settings.

Please realise that when there is a token available on disk / persistent storage (like your log explains), the plugin will always use that one. It will not use the one in your config, that is only used the very first startup. Therefore, these tokens might not be old, but are neglected as there is already one on disk available.

**Comment by bsoener** [comment] 2021-02-07 21:33
ok. will set up the token again. report then

**Comment by QuickSander** [comment] 2021-02-07 22:20
Yes please since I strongly believe every time you thought you refreshed the tokens, it actually did not and remained stuck to the database token.

It still remains a mystery though why the previous token did not auto refresh, but that could be for many reasons (server of for longer than 10min or so right at the time the token expired, or,....)

**Comment by bsoener** [comment] 2021-02-08 14:59
08/02/2021, 15:57:13] [Miele@home] Token loaded from persistent storage.
[08/02/2021, 15:57:13] [Miele@home] Discovered device: id: 00013925xxxx, name: Trockner, model: TMV840WP
[08/02/2021, 15:57:13] [Miele@home] Ignoring unsupported device. Device: "Trockner" with raw type value: 2.
[08/02/2021, 15:57:13] [Miele@home] Discovered device: id: 00011912xxxx, name: Waschmaschine, model: WMV960
[08/02/2021, 15:57:13] [Miele@home] Registering new accessory: Waschmaschine

**Comment by QuickSander** [comment] 2021-02-08 15:28
After 60s it should mention a poll request to get the status of your washing machine. 

Could you enable debug logging via the config UI and restart Homebridge to activate it. Then you should see it polling every 60s for status. This gives me more insight why it shows offline.

**Comment by bsoener** [comment] 2021-02-08 15:38
where exactly do I enable debug?

**Comment by QuickSander** [comment] 2021-02-08 19:51
![image](https://user-images.githubusercontent.com/8293085/107273383-435c1180-6a4f-11eb-898e-cfc725673ef9.png)

Via UI: "Homebridge Settings" -> "debug mode". Or start Homebridge with `-D` option.

**Comment by bsoener** [comment] 2021-02-09 04:45
the plugin detects my washing machine as offline although it is on and running.

**Comment by QuickSander** [comment] 2021-02-09 06:25
I really need debug logging for that as I do not recognize that problem and my washer dryer is working fine. 

What exactly is offline? In red text "unreachable" or normal text "Off"/"Aus" or really exactly "offline" (as that I have never seen in HomeKit before). Are you sure there isn't another Washing machine tile hidden somewhere and you are looking at a device from some previous homebridge install?

**Comment by bsoener** [comment] 2021-02-09 15:27
Hi. So now it works. I uninstalled it completely and reconfigured everything and it works now. Thanks for your effort and especially for providing the plugin.
<img width="119" alt="Bildschirmfoto 2021-02-09 um 16 25 49" src="https://user-images.githubusercontent.com/77502899/107385807-896ab100-6af3-11eb-9336-b1a00726b114.png">


How is it actually when I have a washing machine and a dryer that run simultaneously. Is then only one window displayed in the Homekit or are there 2?

**Comment by QuickSander** [comment] 2021-02-09 19:02
In the upcoming version I added support for dryers. 
When I release it you should see a second water tap which represents your dryer.

**Comment by QuickSander** [comment] 2021-02-14 13:25
Dryer supported in latest release v2.4.0. I will close this issue for now.

**Closed by QuickSander** 2021-02-14 13:25 UTC
Labels: help wanted
